debug = false
log_file = "/yuwiki/logs/yuwiki.log"
log_file_max_count = 100
session_cookie = "wiki.session"
secret = "yupaits"
session_auth = "user"

[http]
port = "8888"
favicon = "./ui/dist/favicon.ico"
static_path = "./ui/dist/static"
html_path_pattern = "ui/dist/*.html"

[dataSource]
dialect = "sqlite3"
url = "/yuwiki/db/yuwiki.db"
ddl_update = true

[cron]
backup = "0 0 11 * * *"

[path]
upload_path = "/yuwiki/upload/"
backup_path = "/yuwiki/backup/"